/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { mediasApi } from '../api/api';
import type {
  GetMediaWithFilterParams,
  MediaDTO,
  PlatformDTO,
} from '../entities/media';

export const createMedias = (mediaDTO: MediaDTO[]) => {
  return mediasApi<boolean>({
    url: `/list`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: mediaDTO,
  });
};

export const getMediaWithFilter = (params?: GetMediaWithFilterParams) => {
  return mediasApi<MediaDTO[]>({ url: `/`, method: 'get', params });
};

export const createMedia = (mediaDTO: MediaDTO) => {
  return mediasApi<boolean>({
    url: `/`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: mediaDTO,
  });
};

export const getMediaById = (id: string) => {
  return mediasApi<MediaDTO>({ url: `/${id}`, method: 'get' });
};

export const deleteMediaById = (id: string) => {
  return mediasApi<boolean>({ url: `/${id}`, method: 'delete' });
};

export const getMediaPlatform = (id: string) => {
  return mediasApi<PlatformDTO[]>({ url: `/${id}/platform`, method: 'get' });
};

export const helloWorld = () => {
  return mediasApi<string>({ url: `/helloWorld`, method: 'get' });
};

export const getGenres = () => {
  return mediasApi<string[]>({ url: `/genres`, method: 'get' });
};

export type CreateMediasResult = NonNullable<
  Awaited<ReturnType<typeof createMedias>>
>;
export type GetMediaWithFilterResult = NonNullable<
  Awaited<ReturnType<typeof getMediaWithFilter>>
>;
export type CreateMediaResult = NonNullable<
  Awaited<ReturnType<typeof createMedia>>
>;
export type GetMediaByIdResult = NonNullable<
  Awaited<ReturnType<typeof getMediaById>>
>;
export type DeleteMediaByIdResult = NonNullable<
  Awaited<ReturnType<typeof deleteMediaById>>
>;
export type GetMediaPlatformResult = NonNullable<
  Awaited<ReturnType<typeof getMediaPlatform>>
>;
export type HelloWorldResult = NonNullable<
  Awaited<ReturnType<typeof helloWorld>>
>;
export type GetGenresResult = NonNullable<
  Awaited<ReturnType<typeof getGenres>>
>;
