/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { mediaApi } from '../api/mediaApi';
import type { GetMediaWithFilterParams, MediaDTO } from '../entities/media';

export const getMediaWithFilter = (params?: GetMediaWithFilterParams) => {
  return mediaApi<MediaDTO[]>({ url: `/api/medias`, method: 'get', params });
};

export const createMedia = (mediaDTO: MediaDTO) => {
  return mediaApi<boolean>({
    url: `/api/medias`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: mediaDTO,
  });
};

export const getMediaById = (id: string) => {
  return mediaApi<MediaDTO>({ url: `/api/medias/${id}`, method: 'get' });
};

export const helloWorld = () => {
  return mediaApi<string>({ url: `/api/medias/helloWorld`, method: 'get' });
};

export type GetMediaWithFilterResult = NonNullable<
  Awaited<ReturnType<typeof getMediaWithFilter>>
>;
export type CreateMediaResult = NonNullable<
  Awaited<ReturnType<typeof createMedia>>
>;
export type GetMediaByIdResult = NonNullable<
  Awaited<ReturnType<typeof getMediaById>>
>;
export type HelloWorldResult = NonNullable<
  Awaited<ReturnType<typeof helloWorld>>
>;
