/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { mediasApi } from '../api/api';
import type { GetMediaWithFilterParams, MediaDTO } from '../entities/media';

export const getMediaWithFilter = (params?: GetMediaWithFilterParams) => {
  return mediasApi<MediaDTO[]>({ url: `/`, method: 'get', params });
};

export const createMedia = (mediaDTO: MediaDTO) => {
  return mediasApi<boolean>({
    url: `/`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: mediaDTO,
  });
};

export const getMediaById = (id: string) => {
  return mediasApi<MediaDTO>({ url: `/${id}`, method: 'get' });
};

export const helloWorld = () => {
  return mediasApi<string>({ url: `/helloWorld`, method: 'get' });
};

export type GetMediaWithFilterResult = NonNullable<
  Awaited<ReturnType<typeof getMediaWithFilter>>
>;
export type CreateMediaResult = NonNullable<
  Awaited<ReturnType<typeof createMedia>>
>;
export type GetMediaByIdResult = NonNullable<
  Awaited<ReturnType<typeof getMediaById>>
>;
export type HelloWorldResult = NonNullable<
  Awaited<ReturnType<typeof helloWorld>>
>;
