/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface CustomResponseUser {
  message?: string;
  code?: string;
  object?: User;
}
