/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface ErrorResponseUser {
  message?: string;
  code?: string;
  object?: User;
}
