/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface User {
  id?: number;
  pseudo: string;
  email: string;
  password: string;
}
