/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetMediaWithFilterParams = {
  page: number;
  size: number;
  search?: string;
};
