/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MediaDTO {
  id?: number;
  type?: string;
  name?: string;
  genres?: string[];
  releaseDate?: string;
  director?: string;
  writers?: string[];
  stars?: string[];
  description?: string;
  imgUrl?: string;
}
